---
baseURL: "/"
languageCode: fr-fr
title: petitmarketeur
module:
  imports:
  - path: github.com/theNewDynamic/gohugo-theme-ananke
DefaultContentLanguage: en
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  custom_css: ["src/main.css"]
  favicon: "/images/logo-projet-3 copie.png"
  site_logo: "/images/logo-projet-3 copie.png"
  description: The last theme you'll ever need. Maybe.
  facebook: ''
  twitter: https://twitter.com/GoHugoIO
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-black
  featured_image: "/images/image-fond-parralax copie.jpg"
  recent_posts_number: 2
  body_classes: athelas bg-washed-yellow

 
