---
baseURL: "/"
languageCode: fr-fr
title: petitmarketeur
module:
  imports:
  - path: github.com/theNewDynamic/gohugo-theme-ananke
DefaultContentLanguage: en
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: "/images/CORPO35_LOGOTYPE_perfume_Awards_03.png"
  description: The last theme you'll ever need. Maybe.
  facebook: ''
  twitter: https://twitter.com/GoHugoIO
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-red
  featured_image: "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number: 2
  body_classes: athelas
